### ISSUE TITLE
Broken Link: Template Literals VSCode Extension

### ISSUE THREAD

**Issue by karamfd** [n6ai/minze#167]
### Describe the bug

Clicking the [template literals link](https://marketplace.visualstudio.com/items?itemName=julienetie.vscode-template-literal) returns a 404 error.

The correct link is below:

https://marketplace.visualstudio.com/items?itemName=julienetie.vscode-template-literals

### Reproduction

The broken link is in the documentation at the following page:

https://minze.dev/guide/advanced-syntax-highlighting.html

### System Info

```shell
Not relevant in this case as it's a bug in the documentation, not the main project.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/n6ai/minze/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/n6ai/minze/blob/main/.github/CONTRIBUTING.md).
- [X] Read the [docs](https://minze.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/n6ai/minze/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/n6ai/minze/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sergejcodes** [comment]
Is now fixed, thanks for mentioning it!
