### ISSUE TITLE
Lazyload

### ISSUE THREAD

**Issue by KartoffelToby** [n6ai/minze#35]
### Clear and concise description of the problem

Would be nice if there was any kind of code split for the custom elements, to lazyload them

### Suggested solution

```
import('./lib/minze-code').then(({MinzeCode}) => {
    Minze.define('minze-code',MinzeCode);
});
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/n6ai/minze/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/n6ai/minze/blob/main/.github/CONTRIBUTING.md).
- [X] Read the [docs](https://minze.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sergejcodes** [comment]
Code splitting and lazy loading is now part of the Minze Vite dev environment. When running the `build` command all elements are split into separate files.

A quick example using CDN:

```html
<html>
  <head></head>
  <body>
    <!-- custom components -->
    <my-awesome-element></my-awesome-element>
    <my-awesome-element-two></my-awesome-element-two>

    <!-- import and custom component definition -->
    <script type="module">
      const root = '//unpkg.com/my-awesome-package@latest/dist'

      const { defineAll } = await import(`${root}/module.js`)
      const { MyAwesomeElement } = await import(`${root}/lib/my-awesome-element.js`)
      const { MyAwesomeElementTwo } = await import(`${root}/lib/my-awesome-element-two.js`)

      defineAll([MyAwesomeElement, MyAwesomeElementTwo])
    </script>
  </body>
</html>
```
